//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketsIncidencias.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Historial
    {
        public int id_historial { get; set; }
        public string comentario { get; set; }
        public Nullable<System.DateTime> fecha_actualizacion { get; set; }
        public Nullable<int> id_incidencia1 { get; set; }
        public Nullable<int> estado_actualizacion { get; set; }
    
        public virtual Estados Estados { get; set; }
        public virtual Incidencia Incidencia { get; set; }
    }
}
